// Code generated by Hermes. DO NOT EDIT.

package L17

type terminal int

type (
	Binding struct {
		Var Symbol
		Val Value
	}
	Closure struct {
		X Symbol
		L Symbol
		F []Symbol
	}
	EffectPrim    terminal // from L17
	PredicatePrim terminal // from L16
	Primitive     terminal // from L13
	RecBinding    struct {
		Var Symbol
		Val LambdaExpr
	}
	Symbol    terminal // from Lsrc
	ValuePrim terminal // from L17
)

type (
	Const interface {
		Datum
		isConst()
	}
	Int struct{ X int }
	Nil struct{}
)

type (
	Datum  interface{ isDatum() }
	Pair   struct{ Car, Cdr Datum }
	Vector struct{ List []Datum }
)

type (
	Effect      interface{ isEffect() }
	ApplyEffect struct {
		Fun  SimpleExpr
		Args []SimpleExpr
	}
	BeginEffect struct {
		Init []Effect
		X    Effect
	}
	IfEffect struct {
		Cond       Predicate
		Then, Else Effect
	}
	LetEffect struct {
		Bindings []Binding
		Body     Effect
	}
	Nop        struct{}
	PrimEffect struct {
		Prim EffectPrim
		Args []SimpleExpr
	}
)

type (
	LabelsBody interface{ isLabelsBody() }
)

type (
	LambdaExpr interface{ isLambdaExpr() }
	Lambda     struct {
		Params []Symbol
		Body   Value
	}
)

type (
	Predicate interface{ isPredicate() }
	BeginPred struct {
		Init []Effect
		X    Predicate
	}
	False   struct{}
	IfPred  struct{ Cond, Then, Else Predicate }
	LetPred struct {
		Bindings []Binding
		Body     Predicate
	}
	PrimPred struct {
		Prim PredicatePrim
		Args []SimpleExpr
	}
	True struct{}
)

type (
	Program interface{ isProgram() }
	Labels  struct {
		Bindings []RecBinding
		Entry    Symbol
	}
)

type (
	SimpleExpr interface {
		Value
		isSimpleExpr()
	}
	Label struct{ Name Symbol }
	Quote struct{ X Const }
)

type (
	Value interface{ isValue() }
	Alloc struct {
		Tag  int64
		Size SimpleExpr
	}
	ApplyValue struct {
		Fun  SimpleExpr
		Args []SimpleExpr
	}
	BeginValue struct {
		Init []Effect
		X    Value
	}
	IfValue struct {
		Cond       Predicate
		Then, Else Value
	}
	LetValue struct {
		Bindings []Binding
		Body     Value
	}
	PrimValue struct {
		Prim ValuePrim
		Args []SimpleExpr
	}
)

func (Int) isConst()           {}
func (Int) isDatum()           {}
func (Nil) isConst()           {}
func (Nil) isDatum()           {}
func (Pair) isDatum()          {}
func (Vector) isDatum()        {}
func (ApplyEffect) isEffect()  {}
func (BeginEffect) isEffect()  {}
func (IfEffect) isEffect()     {}
func (LetEffect) isEffect()    {}
func (Nop) isEffect()          {}
func (PrimEffect) isEffect()   {}
func (Lambda) isLambdaExpr()   {}
func (BeginPred) isPredicate() {}
func (False) isPredicate()     {}
func (IfPred) isPredicate()    {}
func (LetPred) isPredicate()   {}
func (PrimPred) isPredicate()  {}
func (True) isPredicate()      {}
func (Labels) isProgram()      {}
func (Label) isSimpleExpr()    {}
func (Label) isValue()         {}
func (Quote) isSimpleExpr()    {}
func (Quote) isValue()         {}
func (Symbol) isSimpleExpr()   {}
func (Symbol) isValue()        {}
func (Alloc) isValue()         {}
func (ApplyValue) isValue()    {}
func (BeginValue) isValue()    {}
func (IfValue) isValue()       {}
func (LetValue) isValue()      {}
func (PrimValue) isValue()     {}
